EXECUTABLES =
LIBRARIES	= MPU6050
INCLUDES	= MPU6050.h

MPU6050_SOURCES = MPU6050Base.cpp MPU6050.cpp
MPU6050_LIBS    =

PYTHON_PACKAGES = sensors
sensors_MODULES = mpu6050

include $(EMBEDDED_ROOT)/include/Makefile.mk

all: do_all
	@echo " . . . 'all' done" 

install: do_install
	@echo " . . . 'install' done" 

upload: do_upload
	@echo " . . . 'upload' done" 

clean: do_clean
	@echo " . . . 'clean' done" 

#___oOo___
