#        _    _
#    ___| |  | |_   _  __ _  __ _ _ __ 
#   / _ \ |  | | | | |/ _` |/ _` | '__|
#  |  __/ |  | | |_| | (_| | (_| | |
#   \___|_|  |_|\__,_|\__, |\__,_|_|
#                       (__|
# 
#  Copyright (C) 2026 rodrigo amestica
#  SPDX-License-Identifier: Apache-2.0

add_library(mac STATIC src/fpga_cmd.c)
target_include_directories(mac PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_link_libraries(mac PUBLIC i2c)

#___oOo___
