LIBRARIES	= IMU
INCLUDES	= IMU.h

#DEBUG=on

IMU_SOURCES = Device.cpp
IMU_LIBS    =

include $(EMBEDDED_ROOT)/include/Makefile.mk

all: do_all
	@echo " . . . 'all' done" 

install: do_install
	@echo " . . . 'install' done" 

upload: do_upload
	@echo " . . . 'upload' done" 

clean: do_clean
	@echo " . . . 'clean' done" 

#___oOo___
