TARGET_MEMORY=ROM
#USE_SYSTEM_VIEW=on

EXECUTABLES_L = TurnigyHAL

TurnigyHAL_SOURCES = TurnigyHAL.cpp

include $(EMBEDDED_ROOT)/include/Makefile.mk

all: do_all
	@echo " . . . 'all' done" 

install: do_install
	@echo " . . . 'install' done" 

upload: do_upload
	@echo " . . . 'upload' done" 

reset: do_reset
	@echo " . . . 'reset' done" 

clean: do_clean
	@echo " . . . 'clean' done" 

#___oOo___
