EXECUTABLES_L = pwm normal 
LIBRARIES	  =
INCLUDES	  =

normal_SOURCES = normal.cpp

pwm_SOURCES = pwm.cpp

include $(EMBEDDED_ROOT)/include/Makefile.mk

all: do_all
	@echo " . . . 'all' done" 

install: do_install
	@echo " . . . 'install' done" 

upload: do_upload
	@echo " . . . 'upload' done" 

clean: do_clean
	@echo " . . . 'clean' done" 

#___oOo___
