LIBRARIES  = Queue
INCLUDES   = Queue.h

Queue_SOURCES = Queue.cpp
Queue_LIBS    =

include $(EMBEDDED_ROOT)/include/Makefile.mk

all: do_all
	@echo " . . . 'all' done" 

install: do_install
	@echo " . . . 'install' done" 

upload: do_upload
	@echo " . . . 'upload' done" 

clean: do_clean
	@echo " . . . 'clean' done" 

#___oOo___
