include $(ARDUINO_MODULES)/Makefile.defs

TARGET = periodicReadout
ARDUINO_LIBS   = Wire					\
		 SampleStatistics			\
		 Sensors/L3G4200D			\
		 Sunkee10DOF				\
		 Contributed/i2cdevlib/Arduino/I2Cdev	\
		 Contributed/i2cdevlib/Arduino/L3G4200D	\
		 Contributed/i2cdevlib/Arduino/ADXL345 	\
		 Contributed/i2cdevlib/Arduino/HMC5883L	\
		 Contributed/i2cdevlib/Arduino/BMP085 

include $(ARDUINO_MODULES)/Makefile.base
