EXECUTABLES =
LIBRARIES   = Host
INCLUDES    = Host.h

#DEBUG=on

Host_SOURCES = Host.cpp DataStream.cpp CommandReply.cpp
Host_LIBS    =

include $(EMBEDDED_ROOT)/include/Makefile.mk

all: do_all
	@echo " . . . 'all' done" 

install: do_install
	@echo " . . . 'install' done" 

upload: do_upload
	@echo " . . . 'upload' done" 

clean: do_clean
	@echo " . . . 'clean' done" 

#___oOo___
