include $(ARDUINO_MODULES)/Makefile.defs

TARGET = integrate
ARDUINO_LIBS += Sensors/ADXL345			\
		Sensors/L3G4200D		\
		Sensors/HMC5883L		\
		Control/Filters/FirstOrder	\
		Control/Filters/Complementary	\
		Control/IMU

include $(ARDUINO_MODULES)/Makefile.base
