EXECUTABLES_L = ppm rc throttle pwm calibrateESC

calibrateESC_SOURCES = calibrateESC.cpp

ppm_SOURCES = ppm.cpp

pwm_SOURCES = pwm.cpp

rc_SOURCES = rc.cpp

throttle_SOURCES = throttle.cpp

include $(EMBEDDED_ROOT)/include/Makefile.mk

all: do_all
	@echo " . . . 'all' done" 

install: do_install
	@echo " . . . 'install' done" 

upload: do_upload
	@echo " . . . 'upload' done" 

clean: do_clean
	@echo " . . . 'clean' done" 

#___oOo___
