EXECUTABLES =
LIBRARIES	= PWM
INCLUDES	= PWM.h

#DEBUG=on

PWM_SOURCES = PWM.cpp

include $(EMBEDDED_ROOT)/include/Makefile.mk

all: do_all
	@echo " . . . 'all' done" 

install: do_install
	@echo " . . . 'install' done" 

upload: do_upload
	@echo " . . . 'upload' done" 

clean: do_clean
	@echo " . . . 'clean' done" 

#___oOo___
