EXECUTABLES =
LIBRARIES   = Filter
INCLUDES    = Complementary.h FirstOrder.h

#DEBUG=on

Filter_SOURCES = Complementary.cpp
_LIBS    =

include $(EMBEDDED_ROOT)/include/Makefile.mk

all: do_all
	@echo " . . . 'all' done" 

install: do_install
	@echo " . . . 'install' done" 

upload: do_upload
	@echo " . . . 'upload' done" 

clean: do_clean
	@echo " . . . 'clean' done" 

#___oOo___
