EXECUTABLES =
LIBRARIES	= PID
INCLUDES	= PID.h

#DEBUG=on

PID_SOURCES = PID.cpp CascadePID.cpp

include $(EMBEDDED_ROOT)/include/Makefile.mk

all: do_all
	@echo " . . . 'all' done" 

install: do_install
	@echo " . . . 'install' done" 

upload: do_upload
	@echo " . . . 'upload' done" 

clean: do_clean
	@echo " . . . 'clean' done" 

#___oOo___
