LIBRARIES	  = MainLoop
INCLUDES	  = MainLoop.h

MainLoop_SOURCES = MainLoop.cpp
MainLoop_LIBS	 =

SCRIPTS = mainLoop.py

include $(EMBEDDED_ROOT)/include/Makefile.mk

all: do_all
	@echo " . . . 'all' done" 

install: do_install
	@echo " . . . 'install' done" 

upload: do_upload
	@echo " . . . 'upload' done" 

clean: do_clean
	@echo " . . . 'clean' done" 

#___oOo___
